version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
      eslint:
        patterns:
          - "eslint"
          - "@types/eslint"
      markdown-it:
        patterns:
          - "markdown-it"
          - "@types/markdown-it"
      sanitize-html:
        patterns:
          - "sanitize-html"
          - "@types/sanitize-html"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
    open-pull-requests-limit: 20
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
