name: Assign author

on: pull_request

permissions:
  pull-requests: write
  # There is a bug with the github cli pr edit function which makes it require the repository-projects permission
  repository-projects: read

jobs:
  assign-author:
    name: Assign PR to author
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Assign
        id: assign
        run: gh pr edit ${{ github.event.pull_request.html_url }} --add-reviewer kdmcguire
