name: CI

on: [pull_request, merge_group]

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node
        id: node
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
      - name: Install
        id: install
        run: npm ci
      - name: Astro check
        id: astro
        run: npm run check
      - name: Build
        id: build
        run: npm run build
  auto-approve:
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs: [checks]
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
