name: CI

on: [pull_request, merge_group]

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup npm
        id: node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Install
        id: install
        run: npm ci
      - name: Astro check
        id: check
        run: npm run check
