# ./.github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    - cron: "0 * * * *" # Once an hour at minute 0
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: POST to Build Hook
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/ ${{ secrets.NETLIFY_BUILD_HOOK }}
